services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
  mysql_db:
      image: mysql:8.2
      env_file: ./app/.env
      ports:
          - 3306:3306
      volumes:
          - mysql_data:/var/lib/mysql
volumes:
    mysql_data: